#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "owntracks"
name = "OwnTracks"
description.en = "Keep track of your location history"
description.fr = "Gérez votre historique de géolocalisation"

version = "2.12.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://owntracks.org/"
code = "https://github.com/owntracks/frontend"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/owntracks"

    [install.user]
    ask.en = "Choose an account"
    ask.fr = "Choisissez un compte"
    help.en = "Mandatory if the app is set to public: this account's traces will be loaded by default."
    help.fr = "Obligatoire si l'app est publique : les traces de ce compte seront chargées par défaut."
    type = "user"
    optional = true

    [install.init_main_permission]
    type = "group"
    default = "all_users"
    help.en = "Be wary if you select Visitors: all locations sent to the recorder can be read."
    help.fr = "Attention si vous sélectionnez Visiteurs : toutes les localisations envoyées à l'enregistreur pourront être lues."

[resources]
    [resources.apt]
    extras.recorder.repo = "deb http://repo.owntracks.org/debian __YNH_DEBIAN_VERSION__ main"
    extras.recorder.key = "https://raw.githubusercontent.com/owntracks/recorder/master/etc/repo.owntracks.org.gpg.key"
    extras.recorder.packages = ["ot-recorder"]

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.sources.main]
    url = "https://github.com/owntracks/frontend/archive/refs/tags/v2.12.0.tar.gz"
    sha256 = "1695c3e39f5b276fc6d07c7685eaa3df033e37979b240bc8422663e8aa22e130"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "tarball"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.auth_header = false
    api.show_tile = false
    api.protected= true
