packaging_format = 2

id = "owntracks"
name = "OwnTracks"
description.en = "Keep track of your location history"
description.fr = "Gérez votre historique de géolocalisation"

version = "0.1~ynh10"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0"
website = "https://owntracks.org/"
code = "https://github.com/tomyvi/php-owntracks-recorder"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.3.0"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/owntracks"

    [install.user]
    ask.en = "Choose a user"
    ask.fr = "Choisissez un utilisateur"
    help.en = "Mandatory if the app is set to public. This user's traces will be displayed to visitors."
    help.fr = "Obligatoire si l'app est publique. Les traces de cet utilisateur seront montrées aux visiteurs."
    type = "user"
    optional = true

    [install.init_main_permission]
    help.en = "If public, anyone will be able to see the owntracks record from specified user."
    help.fr = "Si publique, quiconque aura accès aux traces owntracks de l'utilisateur spécifié."
    type = "group"
    default = false

[resources]
        [resources.sources.main]
        url = "https://github.com/tituspijean/php-owntracks-recorder/archive/v0.1-beta.8.zip"
        sha256 = "9C8E4F15E15FF7C57361A5E90C56389D271C41B11B7290D956F5F63875F729D8"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.database]
    type = "mysql"
