#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# Cleanup previous package that ynh_setup_source on install_dir --full_replace=1
if [ ! -d "$install_dir/www" ]; then
    ynh_secure_remove "$install_dir"/* "$install_dir"/.*
fi

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Updating NodeJS..." --weight=7

# Install Nodejs
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/source" --full_replace=1

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# INSTALL THE LOUNGE
#=================================================
ynh_script_progression --message="Installing $app..." --weight=10

pushd "$install_dir/source"
    ynh_use_nodejs
    ynh_exec_warn_less ynh_exec_as "$app" env "$ynh_node_load_PATH" yarn install
    ynh_exec_warn_less ynh_exec_as "$app" env "$ynh_node_load_PATH" NODE_ENV=production yarn build
popd

mv "$install_dir/source/dist" "$install_dir/www"
ynh_secure_remove "$install_dir/source"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="config.example.js" --destination="$install_dir/www/config/config.js"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

chmod 400 "$install_dir/www/config/config.js"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..."

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
