#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Updating NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir/source" --full_replace

#=================================================
# INSTALL THE LOUNGE
#=================================================
ynh_script_progression "Installing $app..."

ynh_safe_rm "$install_dir/www"

pushd "$install_dir/source"
    ynh_hide_warnings ynh_exec_as_app npm install
    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production npm build
popd

mv "$install_dir/source/dist" "$install_dir/www"
ynh_safe_rm "$install_dir/source"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding configuration files..."

ynh_config_add --template="config.example.js" --destination="$install_dir/www/config/config.js"

ynh_config_add --template="env" --destination="$install_dir/.env"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_systemd

mkdir -p "/var/log/$app/"

yunohost service add "$app" --description="Owntracks recorder" --log="/var/log/$app/$app.log"

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
